import {
    OPTION_SUBMITE,
    ADD_CATEGORY,
    REMOVE_CATEGORY,
    RANDOM_CHECK,
    NEW_CHECK,
    WRONGS_CHECK,
    EMPTYS_CHECK,
    LENGTH_UPDATE,
    RESULT_VALUE,
} from './Options'
import {
    SELECT_ANSWER,
    NEW_QUEST,
} from './Questions'


export {
    OPTION_SUBMITE,
    ADD_CATEGORY,
    REMOVE_CATEGORY,
    RANDOM_CHECK,
    NEW_CHECK,
    WRONGS_CHECK,
    EMPTYS_CHECK,
    LENGTH_UPDATE,
    RESULT_VALUE,
    SELECT_ANSWER,
    NEW_QUEST,
}